name: build CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 모든 의존성 설치
        run: yarn
      - name: 모든 패키지 빌드
        run: yarn build

  dependabot:
    name: 'Dependabot'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
